name: Check Website Build
on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    uses: OWASP/mas-website/.github/workflows/build-website-reusable.yml@main
    with:
      deploy: false
      sources_override_json: ${{ format('{{"OWASP/mastg":"refs/heads/{0}"}}', github.head_ref) }}
